### PR TITLE
use a static version of ansible since current latest is borked

### PR DESCRIPTION
**Pull request by l1ll1**

### CODE REVIEW

**Comment by serine** [comment]
@l1ll1 this is great idea, but can you make a variable in group_vars/all `ansible_version: 2.2.1.0` and use that variable instead of hard coding the version `{{ ansible_version }}` thanks

**Comment by l1ll1** [comment]
Done

**Comment by serine** [comment]
sorry to be a pain, but `"{{ ansible_version }}"` gotta be quoted I think

**Comment by serine** [comment]
did you test it and it works? I'll pull it in if it does

**Comment by serine** [comment]
great, thanks heaps

**Pull request merged**
